// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdqpevalmayduojaglqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkcXBldmFsbWF5ZHVvamFnbHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0MzA2NDcsImV4cCI6MjA1MDAwNjY0N30.lRw_NSRyjHjHCeuNEmLAWY2dgV59FoiadASVj4RfJeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);